# Generated by Django 3.2.13 on 2023-07-10 12:17

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afo', '0007_auto_20180323_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenementafo',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='lieuafo',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
    ]
