# Generated by Django 4.2.18 on 2026-05-13 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('afo', '0001_squashed_0009_add_autocomplete_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenementafo',
            name='autocomplete_vector',
        ),
        migrations.RemoveField(
            model_name='evenementafo',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='lieuafo',
            name='autocomplete_vector',
        ),
        migrations.RemoveField(
            model_name='lieuafo',
            name='search_vector',
        ),
        migrations.AlterField(
            model_name='evenementafo',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire'),
        ),
        migrations.AlterField(
            model_name='lieuafo',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire'),
        ),
    ]
