# Generated by Django 4.2.18 on 2026-05-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afo', '0010_remove_evenementafo_search_vector_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evenementafo',
            name='autocomplete_vector',
        ),
        migrations.RemoveField(
            model_name='lieuafo',
            name='autocomplete_vector',
        ),
    ]
