services:
  postgresql:
    build:
      context: ..
      dockerfile: postgresql.Dockerfile
    image: $PROJECT/postgresql:${IMAGES_TAG:-latest}
    environment:
      # FIXME: Remove when upgrading to a more recent PostgreSQL version.
      POSTGRES_INITDB_ARGS:
    shm_size: 512mb
    deploy:
      resources:
        limits:
          memory: 3000M
  redis:
    image: $PROJECT/redis:${IMAGES_TAG:-latest}
    build:
      context: ..
      dockerfile: redis.Dockerfile
    volumes:
      - redis-data:/data
      - redis-socket:/var/run/redis
    network_mode: none
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 1s
      retries: 60
  elasticsearch:
    # FIXME: Use the alpine image when it is more stable (we get incomprehensible mountpoint issues with it).
    image: elasticsearch:1.7.6
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    expose:
      - 9200
    networks:
      internal:
    restart: always
    healthcheck:
      test: wget http://elasticsearch:9200 -q -O - > /dev/null
      interval: 1s
      timeout: 1s
      retries: 60
    # Elasticsearch can fail to boot if the number of open files is too low.
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
  migrate:
    command: sh -c "python manage.py collectstatic --ignore bootstrap/docs/* --no-input && python manage.py migrate"
    volumes:
      - redis-socket:/var/run/redis
      - static:/srv/static
    depends_on:
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 2000M
  rq:
    image: $PROJECT/django:${IMAGES_TAG:-latest}
    command: python manage.py rqworker
    environment:
      PROJECT: $PROJECT
      PROJECT_VERBOSE: $PROJECT_VERBOSE
      DOMAIN: $DOMAIN
      TZ: $TZ
      LOCALE: $LOCALE
      LANGUAGES_CODES: $LANGUAGES_CODES
      EMAIL_ADDRESS: $EMAIL_ADDRESS
    volumes:
      - postgresql-socket:/var/run/postgresql
      - redis-socket:/var/run/redis
      - media:/srv/media
      - static:/srv/static
    secrets:
      - .env.secrets
    networks:
      internal:
    tmpfs:
      - /tmp/
    restart: "always"
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
  django:
    build:
      context: ..
      dockerfile: docker-compose-django/Dockerfile
    volumes:
      - static:/srv/static
      - redis-socket:/var/run/redis
    depends_on:
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      rq:
        condition: service_started
    healthcheck:
      interval: 240s
      timeout: 240s
    deploy:
      resources:
        limits:
          memory: 3000M
  react:
    build:
      context: ../frontend
      dockerfile: ../docker-compose-django/react/Dockerfile
    depends_on:
      django:
        condition: service_healthy
  nginx:
    build:
      context: ..
      dockerfile: docker-compose-django/nginx.Dockerfile
    environment:
      CSP_DEFAULT: "'self' https://analyseweb.huma-num.fr"
      CSP_SCRIPT: "'self' 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com code.jquery.com https://analyseweb.huma-num.fr"
      CSP_IMG: "'self' data: blob: https://cdnjs.cloudflare.com a.tile.openstreetmap.org b.tile.openstreetmap.org c.tile.openstreetmap.org http://www.gravatar.com https://code.jquery.com https://analyseweb.huma-num.fr https://i.ytimg.com"
      CSP_STYLE: "'self' 'unsafe-inline' https://cdnjs.cloudflare.com code.jquery.com"
      CSP_CONNECT: "'self' https://analyseweb.huma-num.fr"
      CSP_FRAME: "'self' https://docs.google.com https://www.youtube.com"
      # TODO: Reduce these limits, they are ludicrous.
      #       For Django they are so high because the admin has gigangitic amounts
      #       of related HTTP queries due to related objects everywhere in events.
      DJANGO_LIMIT_CONN: 20
      DJANGO_LIMIT_REQ_RATE: 20r/s
      DJANGO_LIMIT_REQ_BURST: 400
      DJANGO_LIMIT_REQ_DELAY: 200
      REACT_LIMIT_CONN: 20
      REACT_LIMIT_REQ_RATE: 10r/s
      REACT_LIMIT_REQ_BURST: 50
      REACT_LIMIT_REQ_DELAY: 30
      STATIC_LIMIT_CONN: 100
      STATIC_LIMIT_REQ_RATE: 100r/s
      STATIC_LIMIT_REQ_BURST: 500
      STATIC_LIMIT_REQ_DELAY: 100
    volumes:
      - static:/srv/static


volumes:
  redis-data:
  redis-socket:
  elasticsearch-data:
  static:


secrets:
  .env.secrets:
    file: ../.env.secrets
