include:
  - path:
      - docker-compose-django/base.yaml
      - docker-compose-django/react.yaml
      - custom.yaml
      - docker-compose-django/dev.yaml
      - docker-compose-django/react.dev.yaml
    env_file:
      - docker-compose-django/.env.base
      - .env.base
      - docker-compose-django/.env.dev
      - .env.dev
