# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-25 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libretto', '0051_auto_20200624_1605'),
        ('dossiers', '0003_mptt_to_tree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dossierdevenements',
            old_name='auteurs', new_name='individus',
        ),
        migrations.AlterField(
            model_name='dossierdevenements',
            name='individus',
            field=models.ManyToManyField(blank=True, related_name='dossiers', to='libretto.Individu', verbose_name='individus'),
        ),
    ]
