# Generated by Django 3.2.13 on 2023-04-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0004_auto_20200625_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriededossiers',
            name='cached_related_label',
            field=models.TextField(blank=True, db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='categoriededossiers',
            name='is_cached_related_label_safe',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='dossierdevenements',
            name='cached_related_label',
            field=models.TextField(blank=True, db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='dossierdevenements',
            name='is_cached_related_label_safe',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
