# Generated by Django 3.2.13 on 2023-07-05 21:59

from django.db import migrations
from tree.fields import PathField
from tree.operations import CreateTreeTrigger, RebuildPaths, DeleteTreeTrigger


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0004_auto_20200625_1521'),
    ]

    operations = [
        DeleteTreeTrigger('dossierdevenements'),
        migrations.RemoveField('dossierdevenements', 'path'),
        migrations.AddField(
            model_name='dossierdevenements',
            name='path',
            field=PathField(db_index=True, order_by=['position'], size=None),
        ),
        CreateTreeTrigger('dossierdevenements'),
        RebuildPaths('dossierdevenements'),
    ]
