# Generated by Django 3.2.13 on 2023-07-06 18:33

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0005_migrate_tree'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossierdevenements',
            options={'ordering': ['path'], 'permissions': (('can_change_status', 'Peut changer l’état'),), 'verbose_name': 'dossier d’événements', 'verbose_name_plural': 'dossiers d’événements'},
        ),
        migrations.AlterField(
            model_name='categoriededossiers',
            name='nom',
            field=models.CharField(max_length=75, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='categoriededossiers',
            name='position',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='position'),
        ),
        migrations.AddIndex(
            model_name='dossierdevenements',
            index=models.Index(django.db.models.expressions.RawSQL('path[:array_length(path, 1) - 1]', ()), name='dossiers_path_parent_index'),
        ),
        migrations.AddIndex(
            model_name='dossierdevenements',
            index=models.Index(django.db.models.expressions.F('path__level'), name='dossiers_path_level_index'),
        ),
        migrations.AddIndex(
            model_name='dossierdevenements',
            index=models.Index(django.db.models.expressions.F('path__0_1'), name='dossiers_path_slice_1_index'),
        ),
        migrations.AddIndex(
            model_name='dossierdevenements',
            index=models.Index(django.db.models.expressions.F('path__0_2'), name='dossiers_path_slice_2_index'),
        ),
        migrations.AddIndex(
            model_name='dossierdevenements',
            index=models.Index(django.db.models.expressions.F('path__0_3'), name='dossiers_path_slice_3_index'),
        ),
        migrations.AddIndex(
            model_name='dossierdevenements',
            index=models.Index(django.db.models.expressions.F('path__0_4'), name='dossiers_path_slice_4_index'),
        ),
        migrations.AddIndex(
            model_name='dossierdevenements',
            index=models.Index(django.db.models.expressions.F('path__0_5'), name='dossiers_path_slice_5_index'),
        ),
    ]
