# Generated by Django 3.2.13 on 2023-07-10 10:41

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations
import django.db.models.expressions

from db_search.sql import UpdateAllSearchVectors


class Migration(migrations.Migration):

    dependencies = [
        # FIXME: Enable again when applied in production.
        # ('db_search', '0001_create_search_configurations'),
        ('dossiers', '0006_auto_20230706_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriededossiers',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='dossierdevenements',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='categoriededossiers',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('search_vector'), name='categoriededossiers_search'),
        ),
        migrations.AddIndex(
            model_name='dossierdevenements',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('search_vector'), name='dossierdevenements_search'),
        ),
        UpdateAllSearchVectors('categoriededossiers', ['nom']),
        UpdateAllSearchVectors('dossierdevenements', ['titre', 'titre_court']),
    ]
