# Generated by Django 3.2.13 on 2023-10-03 17:23

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations
import django.db.models.expressions

from db_search.sql import UpdateAllSearchVectors


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0007_add_search_vectors'),
        # FIXME: Enable again when applied in production.
        # ('db_search', '0001_create_search_configurations'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='categoriededossiers',
            name='categoriededossiers_search',
        ),
        migrations.RemoveIndex(
            model_name='dossierdevenements',
            name='dossierdevenements_search',
        ),
        migrations.AddField(
            model_name='categoriededossiers',
            name='autocomplete_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='dossierdevenements',
            name='autocomplete_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='categoriededossiers',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('search_vector'), name='categoriedossiers_search'),
        ),
        migrations.AddIndex(
            model_name='categoriededossiers',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('autocomplete_vector'), name='categoriedossiers_autocomplete'),
        ),
        migrations.AddIndex(
            model_name='dossierdevenements',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('search_vector'), name='dossierevenements_search'),
        ),
        migrations.AddIndex(
            model_name='dossierdevenements',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('autocomplete_vector'), name='dossierevenements_autocomplete'),
        ),
        UpdateAllSearchVectors('categoriededossiers', ['nom']),
        UpdateAllSearchVectors('dossierdevenements', ['titre', 'titre_court']),
    ]
