# Generated by Django 3.2.13 on 2023-10-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0010_dossierdoeuvres'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='dossiers/', verbose_name='logo'),
        ),
    ]
