# Generated by Django 4.2.18 on 2026-05-05 16:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('libretto', '0003_alter_auteur_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0094_alter_page_locale'),
        ('dossiers', '0001_squashed_0012_dossier_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriededossiers',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire'),
        ),
        migrations.CreateModel(
            name='SourcesFilePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('short_title', models.CharField(blank=True, help_text='Utilisé pour le chemin de fer.', max_length=100, verbose_name='titre court')),
                ('publication_date', models.DateField(default=datetime.datetime.now, verbose_name='date de publication')),
                ('publications', models.TextField(blank=True, verbose_name='publication(s) associée(s)')),
                ('developpements', models.TextField(blank=True, verbose_name='développements envisagés')),
                ('presentation', models.TextField(verbose_name='présentation')),
                ('context', models.TextField(blank=True, verbose_name='contexte historique')),
                ('references_and_methodology', models.TextField(blank=True, verbose_name='sources et protocole')),
                ('bibliography', models.TextField(blank=True, verbose_name='bibliographie indicative')),
                ('debut', models.DateField(blank=True, null=True, verbose_name='début')),
                ('fin', models.DateField(blank=True, null=True, verbose_name='fin')),
                ('ensembles', models.ManyToManyField(blank=True, related_name='sourcesfiles', to='libretto.ensemble', verbose_name='ensembles')),
                ('evenements', models.ManyToManyField(blank=True, related_name='sourcesfiles', to='libretto.evenement', verbose_name='événements')),
                ('individus', models.ManyToManyField(blank=True, related_name='sourcesfiles', to='libretto.individu', verbose_name='individus')),
                ('lieux', models.ManyToManyField(blank=True, related_name='sourcesfiles', to='libretto.lieu', verbose_name='lieux')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='logo')),
                ('oeuvres', models.ManyToManyField(blank=True, related_name='sourcesfiles', to='libretto.oeuvre', verbose_name='œuvres')),
                ('parties', models.ManyToManyField(blank=True, related_name='sourcesfiles', to='libretto.partie', verbose_name='parties')),
                ('scientific_editors', models.ManyToManyField(related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='éditeurs scientifiques')),
                ('teaser_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='image d’accroche')),
            ],
            options={
                'verbose_name': 'dossier',
                'verbose_name_plural': 'dossiers',
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
