# Generated by Django 4.2.18 on 2026-05-13 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dossiers', '0001_squashed_0012_dossier_logo'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='categoriededossiers',
            name='categoriedossiers_search',
        ),
        migrations.RemoveIndex(
            model_name='categoriededossiers',
            name='categoriedossiers_autocomplete',
        ),
        migrations.RemoveIndex(
            model_name='dossier',
            name='dossier_search',
        ),
        migrations.RemoveIndex(
            model_name='dossier',
            name='dossier_autocomplete',
        ),
        migrations.RemoveField(
            model_name='categoriededossiers',
            name='autocomplete_vector',
        ),
        migrations.RemoveField(
            model_name='categoriededossiers',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='autocomplete_vector',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='search_vector',
        ),
        migrations.AlterField(
            model_name='categoriededossiers',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire'),
        ),
    ]
