# Generated by Django 4.2.18 on 2026-05-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0013_remove_categoriededossiers_categoriedossiers_search_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='categoriededossiers',
            name='categoriedossiers_autocomplete',
        ),
        migrations.RemoveIndex(
            model_name='dossier',
            name='dossier_autocomplete',
        ),
        migrations.RemoveField(
            model_name='categoriededossiers',
            name='autocomplete_vector',
        ),
        migrations.RemoveField(
            model_name='dossier',
            name='autocomplete_vector',
        ),
    ]
