# Generated by Django 4.2.18 on 2026-06-30 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libretto', '0064_remove_caracteristiquedeprogramme_caracdeprogramme_search_and_more'),
        ('dossiers', '0013_remove_categoriededossiers_categoriedossiers_search_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierDeSources',
            fields=[
                ('dossier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dossiers.dossier')),
                ('debut', models.DateField(blank=True, null=True, verbose_name='début')),
                ('fin', models.DateField(blank=True, null=True, verbose_name='fin')),
                ('ensembles', models.ManyToManyField(blank=True, related_name='dossiersdesources', to='libretto.ensemble', verbose_name='ensembles')),
                ('individus', models.ManyToManyField(blank=True, related_name='dossiersdesources', to='libretto.individu', verbose_name='individus')),
                ('lieux', models.ManyToManyField(blank=True, related_name='dossiersdesources', to='libretto.lieu', verbose_name='lieux')),
                ('oeuvres', models.ManyToManyField(blank=True, related_name='dossiersdesources', to='libretto.oeuvre', verbose_name='œuvres')),
                ('sources', models.ManyToManyField(blank=True, related_name='dossiersdesources', to='libretto.source', verbose_name='sources')),
                ('types', models.ManyToManyField(blank=True, related_name='dossiersdesources', to='libretto.typedesource', verbose_name='types de source')),
            ],
            options={
                'verbose_name': 'dossier de sources',
                'verbose_name_plural': 'dossiers de sources',
                'abstract': False,
            },
            bases=('dossiers.dossier',),
        ),
    ]
