# Generated by Django 4.2.18 on 2026-07-21 11:29, then hand-reordered:
# the three multi-table-inheritance children (DossierDEvenements,
# DossierDOeuvres, DossierDeSources) are merged into the base Dossier.
# Their fields are first renamed to old_* (freeing the names for the new base
# fields while keeping the data), the new base fields are added, the data is
# copied over, and only then are the child models dropped.

import django.contrib.postgres.fields
from django.db import migrations, models

# How each child's fields map onto the merged Dossier:
# (child model name, kind stored in types_de_donnees,
#  {old concrete field -> new field}, {old M2M field -> new M2M field})
CHILD_SPECS = [
    ('DossierDEvenements', 'evenements',
     {'old_debut': 'debut', 'old_fin': 'fin',
      'old_circonstance': 'circonstance'},
     {'old_lieux': 'lieux', 'old_individus': 'individus',
      'old_ensembles': 'ensembles', 'old_saisons': 'saisons',
      'old_oeuvres': 'filtre_oeuvres', 'old_sources': 'filtre_sources',
      'old_evenements': 'evenements'}),
    ('DossierDOeuvres', 'oeuvres',
     {'old_debut': 'debut', 'old_fin': 'fin'},
     {'old_lieux': 'lieux', 'old_individus': 'individus',
      'old_ensembles': 'ensembles', 'old_genres': 'genres',
      'old_sources': 'filtre_sources', 'old_oeuvres': 'oeuvres'}),
    ('DossierDeSources', 'sources',
     {'old_debut': 'debut', 'old_fin': 'fin'},
     {'types': 'types_de_sources', 'old_lieux': 'lieux',
      'old_individus': 'individus', 'old_ensembles': 'ensembles',
      'old_oeuvres': 'filtre_oeuvres', 'old_sources': 'sources'}),
]

CHILD_MODEL_NAMES = [name.lower() for name, _, _, _ in CHILD_SPECS]


def merge_children_into_dossier(apps, schema_editor):
    Dossier = apps.get_model('dossiers', 'Dossier')
    for model_name, kind, concrete_map, m2m_map in CHILD_SPECS:
        Child = apps.get_model('dossiers', model_name)
        for child in Child.objects.all():
            # Update the base row column by column (never through
            # ``child.save()``, which would needlessly rewrite every base
            # column, including the tree ``path``).
            Dossier.objects.filter(pk=child.pk).update(
                types_de_donnees=[kind],
                **{new_name: getattr(child, old_name)
                   for old_name, new_name in concrete_map.items()})
            for old_name, new_name in m2m_map.items():
                getattr(child, new_name).set(getattr(child, old_name).all())

    # The generic foreign keys that could point to one of the child models
    # (the home-page carousel and the users' associated authority) now target
    # the base Dossier, whose rows share the same primary keys.
    ContentType = apps.get_model('contenttypes', 'ContentType')
    child_cts = list(ContentType.objects.filter(
        app_label='dossiers', model__in=CHILD_MODEL_NAMES))
    if child_cts:
        dossier_ct, _ = ContentType.objects.get_or_create(
            app_label='dossiers', model='dossier')
        Diapositive = apps.get_model('dezede', 'Diapositive')
        Diapositive.objects.filter(content_type__in=child_cts).update(
            content_type=dossier_ct)
        HierarchicUser = apps.get_model('accounts', 'HierarchicUser')
        HierarchicUser.objects.filter(content_type__in=child_cts).update(
            content_type=dossier_ct)


class Migration(migrations.Migration):

    dependencies = [
        ('libretto', '0064_remove_caracteristiquedeprogramme_caracdeprogramme_search_and_more'),
        ('dossiers', '0014_dossierdesources'),
        # The other 0014 leaf (django-tree 1.0 binary paths, merged from
        # master): depending on it linearises the migration graph.
        ('dossiers', '0014_django_tree_binary_path'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('dezede', '0011_indexentryextension_alter_diapositive_content_type'),
        ('accounts', '0009_remove_hierarchicuser_hierarchicuser_search_and_more'),
    ]

    operations = [
        # -- 1. Free the field names on the children (keeping their data) -----
        *[
            migrations.RenameField(
                model_name='dossierdevenements',
                old_name=name, new_name=f'old_{name}',
            )
            for name in ('debut', 'fin', 'circonstance', 'lieux', 'oeuvres',
                         'individus', 'evenements', 'ensembles', 'sources',
                         'saisons')
        ],
        *[
            migrations.RenameField(
                model_name='dossierdoeuvres',
                old_name=name, new_name=f'old_{name}',
            )
            for name in ('debut', 'fin', 'lieux', 'genres', 'individus',
                         'ensembles', 'sources', 'oeuvres')
        ],
        # `types` keeps its name: it does not clash with any new base field.
        *[
            migrations.RenameField(
                model_name='dossierdesources',
                old_name=name, new_name=f'old_{name}',
            )
            for name in ('debut', 'fin', 'lieux', 'individus', 'oeuvres',
                         'ensembles', 'sources')
        ],
        # -- 2. Add the merged fields on Dossier ------------------------------
        migrations.AddField(
            model_name='dossier',
            name='circonstance',
            field=models.CharField(blank=True, max_length=100, verbose_name='circonstance'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='debut',
            field=models.DateField(blank=True, null=True, verbose_name='début'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='ensembles',
            field=models.ManyToManyField(blank=True, related_name='dossiers', to='libretto.ensemble', verbose_name='ensembles'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='evenements',
            field=models.ManyToManyField(blank=True, related_name='dossiers', to='libretto.evenement', verbose_name='événements'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='filtre_oeuvres',
            field=models.ManyToManyField(blank=True, related_name='dossiers_filtre', to='libretto.oeuvre', verbose_name='œuvres'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='filtre_sources',
            field=models.ManyToManyField(blank=True, related_name='dossiers_filtre', to='libretto.source', verbose_name='sources'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='fin',
            field=models.DateField(blank=True, null=True, verbose_name='fin'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='dossiers', to='libretto.genredoeuvre', verbose_name='genres d’œuvre'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='individus',
            field=models.ManyToManyField(blank=True, related_name='dossiers', to='libretto.individu', verbose_name='individus'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='lieux',
            field=models.ManyToManyField(blank=True, related_name='dossiers', to='libretto.lieu', verbose_name='lieux'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='oeuvres',
            field=models.ManyToManyField(blank=True, related_name='dossiers', to='libretto.oeuvre', verbose_name='œuvres'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='saisons',
            field=models.ManyToManyField(blank=True, related_name='dossiers', to='libretto.saison', verbose_name='saisons'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='dossiers', to='libretto.source', verbose_name='sources'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='types_de_donnees',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('evenements', 'événements'), ('oeuvres', 'œuvres'), ('sources', 'sources')], max_length=20), blank=True, default=list, help_text='Types de données présentés par ce dossier.', size=None, verbose_name='types de données'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='types_de_sources',
            field=models.ManyToManyField(blank=True, related_name='dossiers', to='libretto.typedesource', verbose_name='types de source'),
        ),
        # -- 3. Copy each child's data onto its base row ----------------------
        migrations.RunPython(merge_children_into_dossier,
                             migrations.RunPython.noop),
        # -- 4. Drop the children ---------------------------------------------
        migrations.RemoveField(
            model_name='dossierdevenements',
            name='dossier_ptr',
        ),
        migrations.RemoveField(
            model_name='dossierdevenements',
            name='old_ensembles',
        ),
        migrations.RemoveField(
            model_name='dossierdevenements',
            name='old_evenements',
        ),
        migrations.RemoveField(
            model_name='dossierdevenements',
            name='old_individus',
        ),
        migrations.RemoveField(
            model_name='dossierdevenements',
            name='old_lieux',
        ),
        migrations.RemoveField(
            model_name='dossierdevenements',
            name='old_oeuvres',
        ),
        migrations.RemoveField(
            model_name='dossierdevenements',
            name='old_saisons',
        ),
        migrations.RemoveField(
            model_name='dossierdevenements',
            name='old_sources',
        ),
        migrations.RemoveField(
            model_name='dossierdoeuvres',
            name='dossier_ptr',
        ),
        migrations.RemoveField(
            model_name='dossierdoeuvres',
            name='old_ensembles',
        ),
        migrations.RemoveField(
            model_name='dossierdoeuvres',
            name='old_genres',
        ),
        migrations.RemoveField(
            model_name='dossierdoeuvres',
            name='old_individus',
        ),
        migrations.RemoveField(
            model_name='dossierdoeuvres',
            name='old_lieux',
        ),
        migrations.RemoveField(
            model_name='dossierdoeuvres',
            name='old_oeuvres',
        ),
        migrations.RemoveField(
            model_name='dossierdoeuvres',
            name='old_sources',
        ),
        migrations.DeleteModel(
            name='DossierDeSources',
        ),
        migrations.DeleteModel(
            name='DossierDEvenements',
        ),
        migrations.DeleteModel(
            name='DossierDOeuvres',
        ),
    ]
