# Generated by Django 3.2.4 on 2021-06-27 21:25

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
from tree.operations import CreateTreeTrigger, RebuildPaths, DeleteTreeTrigger


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0003_mptt_to_tree'),
    ]

    operations = [
        DeleteTreeTrigger('hierarchicuser', parent_field='mentor'),
        migrations.AlterField(
            model_name='hierarchicuser',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('partie', 'profession', 'oeuvre', 'ensemble', 'source', 'lieu', 'evenement', 'individu')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='type d’autorité associée'),
        ),
        migrations.AlterField(
            model_name='hierarchicuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='hierarchicuser',
            name='mentor',
            field=models.ForeignKey(blank=True, limit_choices_to={'willing_to_be_mentor__exact': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciples', to=settings.AUTH_USER_MODEL, verbose_name='responsable scientifique'),
        ),
        migrations.AlterField(
            model_name='hierarchicuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        CreateTreeTrigger('hierarchicuser', parent_field='mentor'),
        RebuildPaths('hierarchicuser'),
    ]
