# Generated by Django 3.2.13 on 2023-07-05 21:57

from django.db import migrations
from tree.fields import PathField
from tree.operations import CreateTreeTrigger, RebuildPaths, DeleteTreeTrigger


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210627_2325'),
    ]

    operations = [
        DeleteTreeTrigger('hierarchicuser'),
        migrations.RemoveField('hierarchicuser', 'path'),
        migrations.AddField(
            model_name='hierarchicuser',
            name='path',
            field=PathField(db_index=True, order_by=['last_name', 'first_name', 'username'], parent_field_name='mentor', size=None),
        ),
        CreateTreeTrigger('hierarchicuser'),
        RebuildPaths('hierarchicuser'),
    ]
