# Generated by Django 3.2.13 on 2023-07-06 18:33

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0005_migrate_tree'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hierarchicuser',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'utilisateur', 'verbose_name_plural': 'utilisateurs'},
        ),
        migrations.AlterField(
            model_name='hierarchicuser',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('individu', 'profession', 'source', 'evenement', 'ensemble', 'partie', 'lieu', 'oeuvre')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='type d’autorité associée'),
        ),
        migrations.AddIndex(
            model_name='hierarchicuser',
            index=models.Index(django.db.models.expressions.RawSQL('path[:array_length(path, 1) - 1]', ()), name='user_path_parent_index'),
        ),
        migrations.AddIndex(
            model_name='hierarchicuser',
            index=models.Index(django.db.models.expressions.F('path__level'), name='user_path_level_index'),
        ),
        migrations.AddIndex(
            model_name='hierarchicuser',
            index=models.Index(django.db.models.expressions.F('path__0_1'), name='user_path_slice_1_index'),
        ),
        migrations.AddIndex(
            model_name='hierarchicuser',
            index=models.Index(django.db.models.expressions.F('path__0_2'), name='user_path_slice_2_index'),
        ),
        migrations.AddIndex(
            model_name='hierarchicuser',
            index=models.Index(django.db.models.expressions.F('path__0_3'), name='user_path_slice_3_index'),
        ),
        migrations.AddIndex(
            model_name='hierarchicuser',
            index=models.Index(django.db.models.expressions.F('path__0_4'), name='user_path_slice_4_index'),
        ),
        migrations.AddIndex(
            model_name='hierarchicuser',
            index=models.Index(django.db.models.expressions.F('path__0_5'), name='user_path_slice_5_index'),
        ),
    ]
