# Generated by Django 3.2.13 on 2023-07-10 10:32

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.expressions

from db_search.sql import UpdateAllSearchVectors


class Migration(migrations.Migration):

    dependencies = [
        # FIXME: Enable again when applied in production.
        # ('db_search', '0001_create_search_configurations'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0006_auto_20230706_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='hierarchicuser',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='hierarchicuser',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('source', 'evenement', 'lieu', 'individu', 'profession', 'ensemble', 'oeuvre', 'partie')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='type d’autorité associée'),
        ),
        migrations.AddIndex(
            model_name='hierarchicuser',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('search_vector'), name='hierarchicuser_search'),
        ),
        UpdateAllSearchVectors('hierarchicuser', ['first_name', 'last_name', 'username', 'email']),
    ]
