# Generated by Django 4.2.18 on 2026-05-13 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0001_squashed_0008_add_autocomplete_vector'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hierarchicuser',
            name='hierarchicuser_search',
        ),
        migrations.RemoveIndex(
            model_name='hierarchicuser',
            name='hierarchicuser_autocomplete',
        ),
        migrations.RenameField(
            model_name='hierarchicuser',
            old_name='object_id',
            new_name='related_object_id',
        ),
        migrations.RemoveField(
            model_name='hierarchicuser',
            name='autocomplete_vector',
        ),
        migrations.RemoveField(
            model_name='hierarchicuser',
            name='search_vector',
        ),
        migrations.AlterField(
            model_name='hierarchicuser',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('ensemble', 'lieu', 'oeuvre', 'partie', 'evenement', 'source', 'individu', 'profession')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='type d’autorité associée'),
        ),
    ]
