# Generated by Django 4.2.18 on 2026-05-12 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0010_rename_object_id_hierarchicuser_related_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchicuser',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('partie', 'lieu', 'oeuvre', 'source', 'evenement', 'ensemble', 'profession', 'individu')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='type d’autorité associée'),
        ),
    ]
