# Generated by Django 4.2.18 on 2026-05-12 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0011_alter_hierarchicuser_content_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hierarchicuser',
            name='hierarchicuser_autocomplete',
        ),
        migrations.RemoveField(
            model_name='hierarchicuser',
            name='autocomplete_vector',
        ),
        migrations.AlterField(
            model_name='hierarchicuser',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ('profession', 'partie', 'ensemble', 'evenement', 'oeuvre', 'individu', 'source', 'lieu')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='type d’autorité associée'),
        ),
    ]
