# Generated by Django 3.2.13 on 2024-04-09 14:56

import db_search.sql
from decimal import Decimal
import dezede.models
from django.conf import settings
import django.contrib.postgres.indexes
import django.contrib.postgres.operations
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions
import image_cropping.fields
import libretto.models.base


class Migration(migrations.Migration):

    replaces = [('dezede', '0001_initial'), ('dezede', '0002_auto_20150419_1816'), ('dezede', '0003_add_unaccent'), ('dezede', '0004_clear_old_revisions'), ('dezede', '0005_add_search_configuration'), ('dezede', '0006_add_search_vector'), ('dezede', '0007_add_autocomplete_configuration'), ('dezede', '0008_add_autocomplete_vector')]

    initial = True

    dependencies = [
        ('contenttypes', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libretto', '0001_initial'),
        ('db_search', '0001_create_search_configurations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diapositive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='identifiant de l’objet lié')),
                ('title', models.CharField(max_length=70, verbose_name='titre')),
                ('subtitle', models.CharField(blank=True, max_length=100, verbose_name='sous-titre')),
                ('text_align', models.CharField(choices=[('text-left', 'Gauche'), ('text-center', 'Centre'), ('text-right', 'Droite')], default='text-left', max_length=11, verbose_name='alignement du texte')),
                ('text_background', models.BooleanField(default=False, help_text='Ajoute un cadre semi-transparent derrière le texte pour faciliter la lecture.', verbose_name='cadre derrière le texte')),
                ('image', models.ImageField(upload_to='accueil', verbose_name='image')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '450x450', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=True, verbose_name='découpage de l’image')),
                ('image_align', models.CharField(choices=[('text-left', 'Gauche'), ('text-center', 'Centre'), ('text-right', 'Droite')], default='text-right', max_length=11, verbose_name='alignement de l’image')),
                ('opacity', models.DecimalField(choices=[(Decimal('1.0'), 'Opaque'), (Decimal('0.9'), '90 %'), (Decimal('0.8'), '80 %'), (Decimal('0.7'), '70 %'), (Decimal('0.6'), '60 %'), (Decimal('0.5'), '50 %'), (Decimal('0.4'), '40 %'), (Decimal('0.3'), '30 %'), (Decimal('0.2'), '20 %'), (Decimal('0.1'), '10 %')], decimal_places=1, default=0.6, max_digits=2, verbose_name='opacité')),
                ('position', models.PositiveSmallIntegerField(default=dezede.models.get_default_position, verbose_name='position')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='type d’objet lié')),
                ('etat', models.ForeignKey(default=libretto.models.base._get_default_etat, on_delete=django.db.models.deletion.PROTECT, to='libretto.etat', verbose_name='état')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diapositive', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
            ],
            options={
                'ordering': ('position',),
                'verbose_name': 'diapositive',
                'verbose_name_plural': 'diapositives',
            },
        ),
        migrations.AddField(
            model_name='diapositive',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='diapositive',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('individu', 'profession', 'membre', 'audio', 'source', 'evenement', 'lieu', 'partie', 'video', 'ensemble', 'oeuvre', 'dossierdevenements', 'hierarchicuser')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='type d’objet lié'),
        ),
        migrations.AddField(
            model_name='diapositive',
            name='autocomplete_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='diapositive',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('membre', 'video', 'hierarchicuser', 'lieu', 'audio', 'oeuvre', 'ensemble', 'dossierdevenements', 'profession', 'partie', 'individu', 'source', 'evenement')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='type d’objet lié'),
        ),
        migrations.AddIndex(
            model_name='diapositive',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('search_vector'), name='diapositive_search'),
        ),
        migrations.AddIndex(
            model_name='diapositive',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('autocomplete_vector'), name='diapositive_autocomplete'),
        ),
    ]
