# Generated by Django 3.2.13 on 2023-04-02 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dezede', '0004_clear_old_revisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='diapositive',
            name='cached_related_label',
            field=models.TextField(blank=True, db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='diapositive',
            name='is_cached_related_label_safe',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='diapositive',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('individu', 'oeuvre', 'lieu', 'dossierdevenements', 'ensemble', 'audio', 'membre', 'partie', 'hierarchicuser', 'evenement', 'profession', 'source', 'video')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='type d’objet lié'),
        ),
    ]
