# Generated by Django 3.2.13 on 2023-07-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dezede', '0004_clear_old_revisions'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TEXT SEARCH DICTIONARY french_stem_including_stopwords (
                TEMPLATE = snowball,
                Language = french
            );
            CREATE TEXT SEARCH CONFIGURATION french_unaccent_including_stopwords (COPY = french);
            ALTER TEXT SEARCH CONFIGURATION french_unaccent_including_stopwords
                ALTER MAPPING FOR hword, hword_part, word
                WITH unaccent, french_stem_including_stopwords;
            ALTER TEXT SEARCH CONFIGURATION french_unaccent_including_stopwords
                ALTER MAPPING FOR asciihword, asciiword, hword_asciipart
                WITH french_stem_including_stopwords;
            """,
            """
            DROP TEXT SEARCH CONFIGURATION french_unaccent_including_stopwords;
            DROP TEXT SEARCH DICTIONARY french_stem_including_stopwords;
            """,
        ),
    ]
