# Generated by Django 3.2.13 on 2023-07-10 11:56

import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dezede', '0005_add_search_configuration'),
        # FIXME: Enable again when applied in production.
        # ('db_search', '0001_create_search_configurations'),
    ]

    operations = [
        migrations.AddField(
            model_name='diapositive',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='diapositive',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('individu', 'profession', 'membre', 'audio', 'source', 'evenement', 'lieu', 'partie', 'video', 'ensemble', 'oeuvre', 'dossierdevenements', 'hierarchicuser')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='type d’objet lié'),
        ),
    ]
