# Generated by Django 3.2.13 on 2023-10-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dezede', '0006_add_search_vector'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TEXT SEARCH CONFIGURATION simple_unaccent (COPY = simple);
            ALTER TEXT SEARCH CONFIGURATION simple_unaccent
                ALTER MAPPING FOR hword, hword_part, word
                WITH unaccent, simple;
            """,
            """
            DROP TEXT SEARCH CONFIGURATION simple_unaccent;
            """,
        ),
    ]
