# Generated by Django 3.2.13 on 2023-10-03 17:26

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions

from common.utils.sql import UpdateAllSearchVectors


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dezede', '0007_add_autocomplete_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='diapositive',
            name='autocomplete_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='diapositive',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('membre', 'video', 'hierarchicuser', 'lieu', 'audio', 'oeuvre', 'ensemble', 'dossierdevenements', 'profession', 'partie', 'individu', 'source', 'evenement')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='type d’objet lié'),
        ),
        migrations.AddIndex(
            model_name='diapositive',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('search_vector'), name='diapositive_search'),
        ),
        migrations.AddIndex(
            model_name='diapositive',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('autocomplete_vector'), name='diapositive_autocomplete'),
        ),
        UpdateAllSearchVectors('diapositive', ['title', 'subtitle']),
    ]
