# Generated by Django 4.2.18 on 2026-05-13 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dezede', '0001_squashed_0008_add_autocomplete_vector'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='diapositive',
            name='diapositive_search',
        ),
        migrations.RemoveIndex(
            model_name='diapositive',
            name='diapositive_autocomplete',
        ),
        migrations.RenameField(
            model_name='diapositive',
            old_name='object_id',
            new_name='related_object_id',
        ),
        migrations.RemoveField(
            model_name='diapositive',
            name='autocomplete_vector',
        ),
        migrations.RemoveField(
            model_name='diapositive',
            name='search_vector',
        ),
        migrations.AlterField(
            model_name='diapositive',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('ensemble', 'dossierdoeuvres', 'lieu', 'dossierdevenements', 'oeuvre', 'dossier', 'partie', 'hierarchicuser', 'membre', 'evenement', 'audio', 'source', 'redirect', 'individu', 'profession', 'video')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='type d’objet lié'),
        ),
        migrations.AlterField(
            model_name='diapositive',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire'),
        ),
    ]
