# Generated by Django 4.2.18 on 2026-05-26 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsearch', '0009_remove_ngram_autocomplete'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('dezede', '0010_add_indexentry_combined_gin_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexEntryExtension',
            fields=[
                ('index_entry_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extension', serialize=False, to='wagtailsearch.indexentry')),
                ('boost', models.FloatField(default=1.0)),
            ],
        ),
        migrations.AlterField(
            model_name='diapositive',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('lieu', 'dossierdoeuvres', 'dossier', 'ensemble', 'partie', 'hierarchicuser', 'profession', 'individu', 'video', 'oeuvre', 'evenement', 'dossierdevenements', 'source', 'membre', 'audio', 'redirect')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='type d’objet lié'),
        ),
    ]
