# Generated by Django 4.2.18 on 2026-05-12 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dezede', '0010_rename_object_id_diapositive_related_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diapositive',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('partie', 'membre', 'lieu', 'dossierdoeuvres', 'hierarchicuser', 'video', 'oeuvre', 'redirect', 'source', 'evenement', 'dossier', 'ensemble', 'profession', 'audio', 'dossierdevenements', 'individu')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='type d’objet lié'),
        ),
    ]
