# Generated by Django 4.2.18 on 2026-07-21 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dezede', '0011_indexentryextension_alter_diapositive_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diapositive',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('profession', 'individu', 'oeuvre', 'source', 'partie', 'ensemble', 'lieu', 'dossier', 'redirect', 'evenement', 'membre', 'hierarchicuser', 'audio', 'video')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='type d’objet lié'),
        ),
    ]
