# Generated by Django 4.2.18 on 2026-05-12 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dezede', '0011_alter_diapositive_content_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='diapositive',
            name='diapositive_autocomplete',
        ),
        migrations.RemoveField(
            model_name='diapositive',
            name='autocomplete_vector',
        ),
        migrations.AlterField(
            model_name='diapositive',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('membre', 'video', 'redirect', 'dossier', 'profession', 'partie', 'ensemble', 'evenement', 'hierarchicuser', 'oeuvre', 'dossierdevenements', 'individu', 'audio', 'source', 'lieu', 'dossierdoeuvres')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='type d’objet lié'),
        ),
    ]
