# Generated by Django 3.2.25 on 2025-09-05 12:44

import correspondence.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('libretto', '0002_auto_20250727_0352'),
        ('correspondence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='edition',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='letter',
            name='recipient_persons',
            field=models.ManyToManyField(related_name='received_letters', through='correspondence.LetterRecipient', to='libretto.Individu'),
        ),
        migrations.AddField(
            model_name='letter',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='URL d’origine'),
        ),
        migrations.AddField(
            model_name='letter',
            name='storage_call_number',
            field=models.CharField(blank=True, max_length=60, verbose_name='cote'),
        ),
        migrations.AddField(
            model_name='letter',
            name='storage_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stored_letters', to='libretto.lieu'),
        ),
        migrations.AddField(
            model_name='lettercorpus',
            name='teaser_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='image d’accroche'),
        ),
        migrations.AddField(
            model_name='letterindex',
            name='teaser_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='image d’accroche'),
        ),
        migrations.AlterField(
            model_name='letterimage',
            name='references',
            field=wagtail.fields.StreamField([('lieu', correspondence.blocks.PrefetchedChooserBlock('libretto.Lieu', label='Lieu ou institution', select_related=['nature', 'parent'])), ('individu', wagtail.snippets.blocks.SnippetChooserBlock('libretto.Individu', label='Individu')), ('ensemble', wagtail.snippets.blocks.SnippetChooserBlock('libretto.Ensemble', label='Ensemble')), ('oeuvre', correspondence.blocks.PrefetchedChooserBlock('libretto.Oeuvre', label='Œuvre', prefetch_related=['pupitres__partie__oeuvre'], select_related=['genre'])), ('evenement', correspondence.blocks.PrefetchedChooserBlock('libretto.Evenement', label='Événement', select_related=['debut_lieu__parent', 'debut_lieu__nature'])), ('partie', correspondence.blocks.PrefetchedChooserBlock('libretto.Partie', label='Rôle ou instrument', select_related=['oeuvre']))], blank=True, use_json_field=True, verbose_name='références'),
        ),
    ]
