# Generated by Django 3.2.25 on 2025-09-05 16:14

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('libretto', '0002_auto_20250727_0352'),
        ('correspondence', '0002_auto_20250905_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lettercorpus',
            name='description',
        ),
        migrations.RemoveField(
            model_name='letterindex',
            name='description',
        ),
        migrations.AddField(
            model_name='lettercorpus',
            name='content',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock()), ('pages_row', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock(search_index=False), label='Rangée de pages', search_index=False)), ('images_row', wagtail.blocks.StructBlock([('height', wagtail.blocks.ChoiceBlock(choices=[('small', 'petite'), ('default', 'par défaut'), ('large', 'grande')], label='Hauteur', search_index=False)), ('images', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Image', search_index=False)), ('link_url', wagtail.blocks.URLBlock(label='URL du lien', required=False, search_index=False)), ('width', wagtail.blocks.ChoiceBlock(choices=[('narrow', 'étroite'), ('default', 'par défaut'), ('wide', 'large')], label='Largeur', search_index=False))], label='Image'), label='Images', search_index=False))], label='Rangée d’images', search_index=False))], blank=True, use_json_field=True, verbose_name='contenu'),
        ),
        migrations.AddField(
            model_name='letterindex',
            name='content',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock()), ('pages_row', wagtail.blocks.ListBlock(wagtail.blocks.PageChooserBlock(search_index=False), label='Rangée de pages', search_index=False)), ('images_row', wagtail.blocks.StructBlock([('height', wagtail.blocks.ChoiceBlock(choices=[('small', 'petite'), ('default', 'par défaut'), ('large', 'grande')], label='Hauteur', search_index=False)), ('images', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(label='Image', search_index=False)), ('link_url', wagtail.blocks.URLBlock(label='URL du lien', required=False, search_index=False)), ('width', wagtail.blocks.ChoiceBlock(choices=[('narrow', 'étroite'), ('default', 'par défaut'), ('wide', 'large')], label='Largeur', search_index=False))], label='Image'), label='Images', search_index=False))], label='Rangée d’images', search_index=False))], blank=True, use_json_field=True, verbose_name='contenu'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='edition',
            field=models.CharField(blank=True, max_length=50, verbose_name='édition'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='storage_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stored_letters', to='libretto.lieu', verbose_name='lieu de conservation'),
        ),
    ]
