# Generated by Django 3.2.25 on 2025-09-05 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0003_auto_20250905_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lettercorpus',
            old_name='content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='letterindex',
            old_name='content',
            new_name='body',
        ),
    ]
