# Generated by Django 4.2.18 on 2026-03-16 10:50

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0005_alter_letter_writing_date_alter_lettercorpus_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='edition',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='imprimé'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='en ligne (URL)'),
        ),
    ]
