# Generated by Django 3.2.4 on 2021-06-27 21:25

from django.db import migrations, models
import django.db.models.deletion
import examens.models


class Migration(migrations.Migration):

    dependencies = [
        ('libretto', '0053_alter_membre_instrument'),
        ('examens', '0003_auto_20180323_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelsource',
            name='source',
            field=models.OneToOneField(limit_choices_to=examens.models.limit_choices_to_possible_sources, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='libretto.source', verbose_name='source'),
        ),
    ]
