# Generated by Django 3.2.25 on 2025-07-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libretto', '0001_squashed_0063_upgrade_check_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='est_promu',
            field=models.BooleanField(db_index=True, default=False, verbose_name='est dans la bibliothèque'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['position', 'page'], name='libretto_so_positio_a69322_idx'),
        ),
    ]
