# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-30 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libretto', '0039_auto_20180807_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='libretto.Source')),
                ('fichier_ogg', models.FileField(blank=True, editable=False, upload_to='files/ogg/', verbose_name='fichier (OGG)')),
                ('fichier_mpeg', models.FileField(blank=True, editable=False, upload_to='files/mpeg/', verbose_name='fichier (MPEG)')),
                ('extrait', models.FileField(blank=True, upload_to='files/extraits/', verbose_name='extrait')),
                ('extrait_ogg', models.FileField(blank=True, editable=False, upload_to='files/extraits/ogg/', verbose_name='extrait (OGG)')),
                ('extrait_mpeg', models.FileField(blank=True, editable=False, upload_to='files/extraits/mpeg/', verbose_name='extrait (MPEG)')),
                ('format', models.CharField(blank=True, editable=False, max_length=10, verbose_name='format')),
                ('format_extrait', models.CharField(blank=True, editable=False, max_length=10, verbose_name='format de l’extrait')),
                ('duree', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='durée de l’extrait (en secondes)')),
                ('duree_extrait', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='durée extrait (en secondes)')),
            ],
            options={
                'verbose_name': 'audio',
                'verbose_name_plural': 'audios',
            },
            bases=('libretto.source',),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('source_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='libretto.Source')),
                ('fichier_ogg', models.FileField(blank=True, editable=False, upload_to='files/ogg/', verbose_name='fichier (OGG)')),
                ('fichier_mpeg', models.FileField(blank=True, editable=False, upload_to='files/mpeg/', verbose_name='fichier (MPEG)')),
                ('extrait', models.FileField(blank=True, upload_to='files/extraits/', verbose_name='extrait')),
                ('extrait_ogg', models.FileField(blank=True, editable=False, upload_to='files/extraits/ogg/', verbose_name='extrait (OGG)')),
                ('extrait_mpeg', models.FileField(blank=True, editable=False, upload_to='files/extraits/mpeg/', verbose_name='extrait (MPEG)')),
                ('format', models.CharField(blank=True, editable=False, max_length=10, verbose_name='format')),
                ('format_extrait', models.CharField(blank=True, editable=False, max_length=10, verbose_name='format de l’extrait')),
                ('duree', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='durée de l’extrait (en secondes)')),
                ('duree_extrait', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='durée extrait (en secondes)')),
                ('largeur', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='largeur')),
                ('hauteur', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='hauteur')),
                ('largeur_extrait', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='largeur de l’extrait')),
                ('hauteur_extrait', models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='hauteur de l’extrait')),
            ],
            options={
                'verbose_name': 'vidéo',
                'verbose_name_plural': 'vidéos',
            },
            bases=('libretto.source',),
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ('parent', 'position', 'date', 'titre', 'numero', 'page', 'lieu_conservation', 'cote'), 'permissions': (('can_change_status', 'Peut changer l’état'),), 'verbose_name': 'source', 'verbose_name_plural': 'sources'},
        ),
        migrations.AddField(
            model_name='source',
            name='fichier',
            field=models.FileField(blank=True, upload_to='files/', verbose_name='fichier'),
        ),
        migrations.AddField(
            model_name='source',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='libretto.Source', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='source',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='source',
            name='type_fichier',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'autre'), (1, 'image'), (2, 'audio'), (3, 'vidéo')], db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='oeuvre',
            name='type_extrait',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'acte'), (2, 'tableau'), (3, 'scène'), (4, 'morceau chanté'), (5, 'partie'), (6, 'livre'), (7, 'album'), (8, 'volume'), (9, 'cahier'), (10, 'ordre'), (11, 'mouvement'), (12, 'pièce de recueil'), (13, 'série')], db_index=True, null=True, verbose_name='type d’extrait'),
        ),
    ]
