# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-30 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libretto', '0041_migrate_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichier',
            name='extract',
        ),
        migrations.RemoveField(
            model_name='fichier',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='fichier',
            name='source',
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ('date', 'titre', 'numero', 'page', 'lieu_conservation', 'cote'), 'permissions': (('can_change_status', 'Peut changer l’état'),), 'verbose_name': 'source', 'verbose_name_plural': 'sources'},
        ),
        migrations.DeleteModel(
            name='Fichier',
        ),
    ]
