# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-05 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libretto', '0042_auto_20190830_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='est_promu',
            field=models.BooleanField(default=False, verbose_name='est dans la bibliothèque'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='duree',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='durée (en secondes)'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='duree_extrait',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='durée de l’extrait (en secondes)'),
        ),
        migrations.AlterField(
            model_name='source',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='À remplir par exemple si la source est une page d’un recueil déjà existant ou un tome d’une série.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='libretto.Source', verbose_name='parent'),
        ),
        migrations.AlterField(
            model_name='source',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Position au sein de son parent.', null=True, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='video',
            name='duree',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='durée (en secondes)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='duree_extrait',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True, verbose_name='durée de l’extrait (en secondes)'),
        ),
    ]
