# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-20 09:22
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libretto', '0045_auto_20191126_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='bibliographie',
            field=models.TextField(blank=True, verbose_name='bibliographie indicative'),
        ),
        migrations.AddField(
            model_name='source',
            name='contexte',
            field=models.TextField(blank=True, verbose_name='contexte historique'),
        ),
        migrations.AddField(
            model_name='source',
            name='date_publication',
            field=models.DateField(default=datetime.datetime.now, verbose_name='date de publication'),
        ),
        migrations.AddField(
            model_name='source',
            name='developpements',
            field=models.TextField(blank=True, verbose_name='développements envisagés'),
        ),
        migrations.AddField(
            model_name='source',
            name='editeurs_scientifiques',
            field=models.ManyToManyField(related_name='sources_editees', to=settings.AUTH_USER_MODEL, verbose_name='éditeurs scientifiques'),
        ),
        migrations.AddField(
            model_name='source',
            name='presentation',
            field=models.TextField(blank=True, verbose_name='présentation'),
        ),
        migrations.AddField(
            model_name='source',
            name='publications',
            field=models.TextField(blank=True, verbose_name='publication(s) associée(s)'),
        ),
        migrations.AddField(
            model_name='source',
            name='sources_et_protocole',
            field=models.TextField(blank=True, verbose_name='sources et protocole'),
        ),
    ]
