# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2019-12-20 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libretto', '0046_auto_20191220_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='telechargement_autorise',
            field=models.BooleanField(default=True, verbose_name='téléchargement autorisé'),
        ),
    ]
