# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-02 18:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libretto', '0047_source_telechargement_autorise'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membre',
            options={'ordering': ('instrument', 'profession', 'classement', 'debut'), 'verbose_name': 'membre', 'verbose_name_plural': 'membres'},
        ),
        migrations.AddField(
            model_name='membre',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='libretto.Profession', verbose_name='profession'),
        ),
        migrations.AlterField(
            model_name='source',
            name='editeurs_scientifiques',
            field=models.ManyToManyField(blank=True, related_name='sources_editees', to=settings.AUTH_USER_MODEL, verbose_name='éditeurs scientifiques'),
        ),
    ]
