# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-11 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libretto', '0049_auto_20200311_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='position',
            field=models.PositiveIntegerField(blank=True, help_text='Position au sein de son parent.', null=True, verbose_name='position'),
        ),
    ]
