# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-10 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libretto', '0051_auto_20200624_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='recette_generale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='recette générale'),
        ),
        migrations.AlterField(
            model_name='partie',
            name='premier_interprete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parties_creees', to='libretto.Individu', verbose_name='premier(ère) interprète'),
        ),
    ]
