# Generated by Django 3.2.4 on 2021-06-27 21:25

from django.db import migrations, models
import django.db.models.deletion
import libretto.models.personnel


class Migration(migrations.Migration):

    dependencies = [
        ('libretto', '0052_auto_20210210_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='instrument',
            field=models.ForeignKey(blank=True, limit_choices_to=libretto.models.personnel.limit_choices_to_instruments, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='libretto.partie', verbose_name='instrument'),
        ),
    ]
