# Generated by Django 3.2.13 on 2023-07-05 21:58

from django.db import migrations
from tree.fields import PathField
from tree.operations import CreateTreeTrigger, RebuildPaths, DeleteTreeTrigger


class Migration(migrations.Migration):

    dependencies = [
        ('libretto', '0053_alter_membre_instrument'),
    ]

    operations = [
        DeleteTreeTrigger('lieu'),
        migrations.RemoveField('lieu', 'path'),
        migrations.AddField(
            model_name='lieu',
            name='path',
            field=PathField(db_index=True, order_by=['nom'], size=None),
        ),
        CreateTreeTrigger('lieu'),
        RebuildPaths('lieu'),
        DeleteTreeTrigger('oeuvre'),
        migrations.RemoveField('oeuvre', 'path'),
        migrations.AddField(
            model_name='oeuvre',
            name='path',
            field=PathField(db_index=True, order_by=['type_extrait', 'numero_extrait', 'titre', 'genre', 'numero', 'coupe', 'incipit', 'tempo', 'tonalite', 'sujet', 'arrangement', 'surnom', 'nom_courant', 'opus', 'ict'], parent_field_name='extrait_de', size=None),
        ),
        CreateTreeTrigger('oeuvre'),
        RebuildPaths('oeuvre'),
    ]
