# Generated by Django 3.2.13 on 2023-04-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libretto', '0053_alter_membre_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='auteur',
            name='cached_related_label',
            field=models.TextField(blank=True, db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='auteur',
            name='is_cached_related_label_safe',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='caracteristiquedeprogramme',
            name='cached_related_label',
            field=models.TextField(blank=True, db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='caracteristiquedeprogramme',
            name='is_cached_related_label_safe',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='elementdedistribution',
            name='cached_related_label',
            field=models.TextField(blank=True, db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='elementdedistribution',
            name='is_cached_related_label_safe',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='elementdeprogramme',
            name='cached_related_label',
            field=models.TextField(blank=True, db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='elementdeprogramme',
            name='is_cached_related_label_safe',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='ensemble',
            name='cached_related_label',
            field=models.TextField(blank=True, db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='ensemble',
            name='is_cached_related_label_safe',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='etat',
            name='cached_related_label',
            field=models.TextField(blank=True, db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='etat',
            name='is_cached_related_label_safe',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='evenement',
            name='cached_related_label',
            field=models.TextField(blank=True, db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='evenement',
            name='is_cached_related_label_safe',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='genredoeuvre',
            name='cached_related_label',
            field=models.TextField(blank=True, db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='genredoeuvre',
            name='is_cached_related_label_safe',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='individu',
            name='cached_related_label',
            field=models.TextField(blank=True, db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='individu',
            name='is_cached_related_label_safe',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='lieu',
            name='cached_related_label',
            field=models.TextField(blank=True, db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='lieu',
            name='is_cached_related_label_safe',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='membre',
            name='cached_related_label',
            field=models.TextField(blank=True, db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='membre',
            name='is_cached_related_label_safe',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='naturedelieu',
            name='cached_related_label',
            field=models.TextField(blank=True, db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='naturedelieu',
            name='is_cached_related_label_safe',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='cached_related_label',
            field=models.TextField(blank=True, db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='is_cached_related_label_safe',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='parentedindividus',
            name='cached_related_label',
            field=models.TextField(blank=True, db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='parentedindividus',
            name='is_cached_related_label_safe',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='parentedoeuvres',
            name='cached_related_label',
            field=models.TextField(blank=True, db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='parentedoeuvres',
            name='is_cached_related_label_safe',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='partie',
            name='cached_related_label',
            field=models.TextField(blank=True, db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='partie',
            name='is_cached_related_label_safe',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='profession',
            name='cached_related_label',
            field=models.TextField(blank=True, db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='profession',
            name='is_cached_related_label_safe',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='pupitre',
            name='cached_related_label',
            field=models.TextField(blank=True, db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='pupitre',
            name='is_cached_related_label_safe',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='saison',
            name='cached_related_label',
            field=models.TextField(blank=True, db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='saison',
            name='is_cached_related_label_safe',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='source',
            name='cached_related_label',
            field=models.TextField(blank=True, db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='source',
            name='is_cached_related_label_safe',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='typedecaracteristiquedeprogramme',
            name='cached_related_label',
            field=models.TextField(blank=True, db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='typedecaracteristiquedeprogramme',
            name='is_cached_related_label_safe',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='typedensemble',
            name='cached_related_label',
            field=models.TextField(blank=True, db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='typedensemble',
            name='is_cached_related_label_safe',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='typedeparentedindividus',
            name='cached_related_label',
            field=models.TextField(blank=True, db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='typedeparentedindividus',
            name='is_cached_related_label_safe',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='typedeparentedoeuvres',
            name='cached_related_label',
            field=models.TextField(blank=True, db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='typedeparentedoeuvres',
            name='is_cached_related_label_safe',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='typedesource',
            name='cached_related_label',
            field=models.TextField(blank=True, db_index=True, editable=False),
        ),
        migrations.AddField(
            model_name='typedesource',
            name='is_cached_related_label_safe',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
