# Generated by Django 3.2.13 on 2023-07-06 18:32

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('libretto', '0054_migrate_tree'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lieu',
            options={'ordering': ['path'], 'permissions': (('can_change_status', 'Peut changer l’état'),), 'verbose_name': 'lieu ou institution', 'verbose_name_plural': 'lieux et institutions'},
        ),
        migrations.AlterModelOptions(
            name='oeuvre',
            options={'ordering': ['path'], 'permissions': (('can_change_status', 'Peut changer l’état'),), 'verbose_name': 'œuvre', 'verbose_name_plural': 'œuvres'},
        ),
        migrations.AddIndex(
            model_name='lieu',
            index=models.Index(django.db.models.expressions.RawSQL('path[:array_length(path, 1) - 1]', ()), name='lieu_path_parent_index'),
        ),
        migrations.AddIndex(
            model_name='lieu',
            index=models.Index(django.db.models.expressions.F('path__level'), name='lieu_path_level_index'),
        ),
        migrations.AddIndex(
            model_name='lieu',
            index=models.Index(django.db.models.expressions.F('path__0_1'), name='lieu_path_slice_1_index'),
        ),
        migrations.AddIndex(
            model_name='lieu',
            index=models.Index(django.db.models.expressions.F('path__0_2'), name='lieu_path_slice_2_index'),
        ),
        migrations.AddIndex(
            model_name='lieu',
            index=models.Index(django.db.models.expressions.F('path__0_3'), name='lieu_path_slice_3_index'),
        ),
        migrations.AddIndex(
            model_name='lieu',
            index=models.Index(django.db.models.expressions.F('path__0_4'), name='lieu_path_slice_4_index'),
        ),
        migrations.AddIndex(
            model_name='lieu',
            index=models.Index(django.db.models.expressions.F('path__0_5'), name='lieu_path_slice_5_index'),
        ),
        migrations.AddIndex(
            model_name='oeuvre',
            index=models.Index(django.db.models.expressions.RawSQL('path[:array_length(path, 1) - 1]', ()), name='oeuvre_path_parent_index'),
        ),
        migrations.AddIndex(
            model_name='oeuvre',
            index=models.Index(django.db.models.expressions.F('path__level'), name='oeuvre_path_level_index'),
        ),
        migrations.AddIndex(
            model_name='oeuvre',
            index=models.Index(django.db.models.expressions.F('path__0_1'), name='oeuvre_path_slice_1_index'),
        ),
        migrations.AddIndex(
            model_name='oeuvre',
            index=models.Index(django.db.models.expressions.F('path__0_2'), name='oeuvre_path_slice_2_index'),
        ),
        migrations.AddIndex(
            model_name='oeuvre',
            index=models.Index(django.db.models.expressions.F('path__0_3'), name='oeuvre_path_slice_3_index'),
        ),
        migrations.AddIndex(
            model_name='oeuvre',
            index=models.Index(django.db.models.expressions.F('path__0_4'), name='oeuvre_path_slice_4_index'),
        ),
        migrations.AddIndex(
            model_name='oeuvre',
            index=models.Index(django.db.models.expressions.F('path__0_5'), name='oeuvre_path_slice_5_index'),
        ),
    ]
