# Generated by Django 3.2.13 on 2023-07-10 11:26

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations
import django.db.models.expressions

from common.utils.sql import UpdateAllSearchVectors


class Migration(migrations.Migration):

    dependencies = [
        ('libretto', '0055_auto_20230706_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typedeparentedindividus',
            options={'ordering': ['classement'], 'verbose_name': 'type de parenté d’individus', 'verbose_name_plural': 'types de parenté d’individus'},
        ),
        migrations.AlterModelOptions(
            name='typedeparentedoeuvres',
            options={'ordering': ['classement'], 'verbose_name': 'type de parenté d’œuvres', 'verbose_name_plural': 'types de parentés d’œuvres'},
        ),
        migrations.AddField(
            model_name='auteur',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='caracteristiquedeprogramme',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='elementdedistribution',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='elementdeprogramme',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ensemble',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='etat',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='evenement',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='genredoeuvre',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='individu',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='naturedelieu',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='oeuvre',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='parentedindividus',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='parentedoeuvres',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='partie',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='pupitre',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='saison',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='typedecaracteristiquedeprogramme',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='typedensemble',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='typedeparentedindividus',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='typedeparentedoeuvres',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='typedesource',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='caracteristiquedeprogramme',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('search_vector'), name='caracdeprogramme_search'),
        ),
        migrations.AddIndex(
            model_name='elementdedistribution',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('search_vector'), name='elementdedistribution_search'),
        ),
        migrations.AddIndex(
            model_name='elementdeprogramme',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('search_vector'), name='elementdeprogramme_search'),
        ),
        migrations.AddIndex(
            model_name='ensemble',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('search_vector'), name='ensemble_search'),
        ),
        migrations.AddIndex(
            model_name='evenement',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('search_vector'), name='evenement_search'),
        ),
        migrations.AddIndex(
            model_name='genredoeuvre',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('search_vector'), name='genredoeuvre_search'),
        ),
        migrations.AddIndex(
            model_name='individu',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('search_vector'), name='individu_search'),
        ),
        migrations.AddIndex(
            model_name='lieu',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('search_vector'), name='lieu_search'),
        ),
        migrations.AddIndex(
            model_name='naturedelieu',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('search_vector'), name='naturedelieu_search'),
        ),
        migrations.AddIndex(
            model_name='oeuvre',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('search_vector'), name='oeuvre_search'),
        ),
        migrations.AddIndex(
            model_name='partie',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('search_vector'), name='partie_search'),
        ),
        migrations.AddIndex(
            model_name='profession',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('search_vector'), name='profession_search'),
        ),
        migrations.AddIndex(
            model_name='pupitre',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('search_vector'), name='pupitre_search'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('search_vector'), name='source_search'),
        ),
        migrations.AddIndex(
            model_name='typedecaracteristiquedeprogramme',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('search_vector'), name='typecaracdeprogramme_search'),
        ),
        migrations.AddIndex(
            model_name='typedensemble',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('search_vector'), name='typedensemble_search'),
        ),
        migrations.AddIndex(
            model_name='typedeparentedindividus',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('search_vector'), name='typedeparentedindividus_search'),
        ),
        migrations.AddIndex(
            model_name='typedeparentedoeuvres',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('search_vector'), name='typedeparentedoeuvres_search'),
        ),
        migrations.AddIndex(
            model_name='typedesource',
            index=django.contrib.postgres.indexes.GinIndex(django.db.models.expressions.F('search_vector'), name='typedesource_search'),
        ),
        UpdateAllSearchVectors('caracteristiquedeprogramme', ['valeur']),
        UpdateAllSearchVectors('elementdedistribution', []),
        UpdateAllSearchVectors('elementdeprogramme', []),
        UpdateAllSearchVectors('ensemble', ['particule_nom', 'nom']),
        UpdateAllSearchVectors('evenement', ['circonstance', 'debut_date', 'debut_heure', 'debut_lieu_approx', 'debut_date_approx', 'debut_heure_approx']),
        UpdateAllSearchVectors('genredoeuvre', ['nom', 'nom_pluriel']),
        UpdateAllSearchVectors('individu', ['nom', 'nom_naissance', 'prenoms', 'pseudonyme']),
        UpdateAllSearchVectors('lieu', ['nom']),
        UpdateAllSearchVectors('naturedelieu', ['nom', 'nom_pluriel']),
        UpdateAllSearchVectors('oeuvre', ['prefixe_titre', 'titre', 'prefixe_titre_secondaire', 'titre_secondaire', 'numero', 'coupe', 'tempo', 'sujet', 'surnom', 'nom_courant', 'incipit', 'opus', 'ict']),
        UpdateAllSearchVectors('partie', ['nom', 'nom_pluriel']),
        UpdateAllSearchVectors('profession', ['nom', 'nom_pluriel', 'nom_feminin', 'nom_feminin_pluriel']),
        UpdateAllSearchVectors('pupitre', []),
        UpdateAllSearchVectors('source', ['titre', 'date', 'date_approx', 'numero', 'lieu_conservation', 'cote']),
        UpdateAllSearchVectors('typedecaracteristiquedeprogramme', ['nom', 'nom_pluriel']),
        UpdateAllSearchVectors('typedensemble', ['nom', 'nom_pluriel']),
        UpdateAllSearchVectors('typedeparentedindividus', ['nom', 'nom_relatif', 'nom_pluriel', 'nom_relatif_pluriel']),
        UpdateAllSearchVectors('typedeparentedoeuvres', ['nom', 'nom_relatif', 'nom_pluriel', 'nom_relatif_pluriel',]),
        UpdateAllSearchVectors('typedesource', ['nom', 'nom_pluriel']),
    ]
