# Generated by Django 3.2.13 on 2023-09-03 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libretto', '0057_alter_oeuvre_sujet'),
    ]

    operations = [
        migrations.AddField(
            model_name='oeuvre',
            name='dedicataire',
            field=models.ForeignKey(blank=True, help_text='N’ajouter que des autorités confirmées. Dans le cas contraire, utiliser les notes.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dedicaces', to='libretto.individu', verbose_name='dédié à'),
        ),
    ]
