# Generated by Django 3.2.13 on 2023-09-05 17:12

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libretto', '0059_oeuvre_dedicataire'),
    ]

    operations = [
        migrations.AddField(
            model_name='oeuvre',
            name='ambitus',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True, verbose_name='ambitus'),
        ),
    ]
